/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MobileEntryRouteImport } from './routes/mobile-entry'
import { Route as IvanOsRouteImport } from './routes/ivan-os'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as EnterpriseCrmRouteImport } from './routes/enterprise-crm'
import { Route as CrmWorkspaceRouteImport } from './routes/crm-workspace'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AuthWorkspaceRouteImport } from './routes/auth-workspace'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as ScheduleDemoSuccessRouteImport } from './routes/schedule-demo.success'
import { Route as CrmLeadsRouteImport } from './routes/crm.leads'
import { Route as CrmContactsRouteImport } from './routes/crm.contacts'
import { Route as CrmCompaniesRouteImport } from './routes/crm.companies'
import { Route as ComplianceSlugRouteImport } from './routes/compliance.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'

const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileEntryRoute = MobileEntryRouteImport.update({
  id: '/mobile-entry',
  path: '/mobile-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const IvanOsRoute = IvanOsRouteImport.update({
  id: '/ivan-os',
  path: '/ivan-os',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseCrmRoute = EnterpriseCrmRouteImport.update({
  id: '/enterprise-crm',
  path: '/enterprise-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmWorkspaceRoute = CrmWorkspaceRouteImport.update({
  id: '/crm-workspace',
  path: '/crm-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWorkspaceRoute = AuthWorkspaceRouteImport.update({
  id: '/auth-workspace',
  path: '/auth-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const ScheduleDemoSuccessRoute = ScheduleDemoSuccessRouteImport.update({
  id: '/schedule-demo/success',
  path: '/schedule-demo/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCompaniesRoute = CrmCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => CrmRoute,
} as any)
const ComplianceSlugRoute = ComplianceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComplianceRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth-workspace': typeof AuthWorkspaceRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/crm-workspace': typeof CrmWorkspaceRoute
  '/enterprise-crm': typeof EnterpriseCrmRoute
  '/insights': typeof InsightsRoute
  '/ivan-os': typeof IvanOsRoute
  '/mobile-entry': typeof MobileEntryRoute
  '/services': typeof ServicesRoute
  '/tenders': typeof TendersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/compliance/$slug': typeof ComplianceSlugRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/schedule-demo/success': typeof ScheduleDemoSuccessRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth-workspace': typeof AuthWorkspaceRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/contact': typeof ContactRoute
  '/crm-workspace': typeof CrmWorkspaceRoute
  '/enterprise-crm': typeof EnterpriseCrmRoute
  '/insights': typeof InsightsRoute
  '/ivan-os': typeof IvanOsRoute
  '/mobile-entry': typeof MobileEntryRoute
  '/services': typeof ServicesRoute
  '/tenders': typeof TendersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/compliance/$slug': typeof ComplianceSlugRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/schedule-demo/success': typeof ScheduleDemoSuccessRoute
  '/crm': typeof CrmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/auth-workspace': typeof AuthWorkspaceRoute
  '/compliance': typeof ComplianceRouteWithChildren
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/crm-workspace': typeof CrmWorkspaceRoute
  '/enterprise-crm': typeof EnterpriseCrmRoute
  '/insights': typeof InsightsRoute
  '/ivan-os': typeof IvanOsRoute
  '/mobile-entry': typeof MobileEntryRoute
  '/services': typeof ServicesRoute
  '/tenders': typeof TendersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/compliance/$slug': typeof ComplianceSlugRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/leads': typeof CrmLeadsRoute
  '/schedule-demo/success': typeof ScheduleDemoSuccessRoute
  '/crm/': typeof CrmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/auth-workspace'
    | '/compliance'
    | '/contact'
    | '/crm'
    | '/crm-workspace'
    | '/enterprise-crm'
    | '/insights'
    | '/ivan-os'
    | '/mobile-entry'
    | '/services'
    | '/tenders'
    | '/admin/bookings'
    | '/admin/settings'
    | '/compliance/$slug'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/leads'
    | '/schedule-demo/success'
    | '/crm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/auth-workspace'
    | '/compliance'
    | '/contact'
    | '/crm-workspace'
    | '/enterprise-crm'
    | '/insights'
    | '/ivan-os'
    | '/mobile-entry'
    | '/services'
    | '/tenders'
    | '/admin/bookings'
    | '/admin/settings'
    | '/compliance/$slug'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/leads'
    | '/schedule-demo/success'
    | '/crm'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/auth-workspace'
    | '/compliance'
    | '/contact'
    | '/crm'
    | '/crm-workspace'
    | '/enterprise-crm'
    | '/insights'
    | '/ivan-os'
    | '/mobile-entry'
    | '/services'
    | '/tenders'
    | '/admin/bookings'
    | '/admin/settings'
    | '/compliance/$slug'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/leads'
    | '/schedule-demo/success'
    | '/crm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  AuthWorkspaceRoute: typeof AuthWorkspaceRoute
  ComplianceRoute: typeof ComplianceRouteWithChildren
  ContactRoute: typeof ContactRoute
  CrmRoute: typeof CrmRouteWithChildren
  CrmWorkspaceRoute: typeof CrmWorkspaceRoute
  EnterpriseCrmRoute: typeof EnterpriseCrmRoute
  InsightsRoute: typeof InsightsRoute
  IvanOsRoute: typeof IvanOsRoute
  MobileEntryRoute: typeof MobileEntryRoute
  ServicesRoute: typeof ServicesRoute
  TendersRoute: typeof TendersRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  ScheduleDemoSuccessRoute: typeof ScheduleDemoSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-entry': {
      id: '/mobile-entry'
      path: '/mobile-entry'
      fullPath: '/mobile-entry'
      preLoaderRoute: typeof MobileEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ivan-os': {
      id: '/ivan-os'
      path: '/ivan-os'
      fullPath: '/ivan-os'
      preLoaderRoute: typeof IvanOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-crm': {
      id: '/enterprise-crm'
      path: '/enterprise-crm'
      fullPath: '/enterprise-crm'
      preLoaderRoute: typeof EnterpriseCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-workspace': {
      id: '/crm-workspace'
      path: '/crm-workspace'
      fullPath: '/crm-workspace'
      preLoaderRoute: typeof CrmWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-workspace': {
      id: '/auth-workspace'
      path: '/auth-workspace'
      fullPath: '/auth-workspace'
      preLoaderRoute: typeof AuthWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/schedule-demo/success': {
      id: '/schedule-demo/success'
      path: '/schedule-demo/success'
      fullPath: '/schedule-demo/success'
      preLoaderRoute: typeof ScheduleDemoSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/companies': {
      id: '/crm/companies'
      path: '/companies'
      fullPath: '/crm/companies'
      preLoaderRoute: typeof CrmCompaniesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/compliance/$slug': {
      id: '/compliance/$slug'
      path: '/$slug'
      fullPath: '/compliance/$slug'
      preLoaderRoute: typeof ComplianceSlugRouteImport
      parentRoute: typeof ComplianceRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ComplianceRouteChildren {
  ComplianceSlugRoute: typeof ComplianceSlugRoute
}

const ComplianceRouteChildren: ComplianceRouteChildren = {
  ComplianceSlugRoute: ComplianceSlugRoute,
}

const ComplianceRouteWithChildren = ComplianceRoute._addFileChildren(
  ComplianceRouteChildren,
)

interface CrmRouteChildren {
  CrmCompaniesRoute: typeof CrmCompaniesRoute
  CrmContactsRoute: typeof CrmContactsRoute
  CrmLeadsRoute: typeof CrmLeadsRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmCompaniesRoute: CrmCompaniesRoute,
  CrmContactsRoute: CrmContactsRoute,
  CrmLeadsRoute: CrmLeadsRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  AuthWorkspaceRoute: AuthWorkspaceRoute,
  ComplianceRoute: ComplianceRouteWithChildren,
  ContactRoute: ContactRoute,
  CrmRoute: CrmRouteWithChildren,
  CrmWorkspaceRoute: CrmWorkspaceRoute,
  EnterpriseCrmRoute: EnterpriseCrmRoute,
  InsightsRoute: InsightsRoute,
  IvanOsRoute: IvanOsRoute,
  MobileEntryRoute: MobileEntryRoute,
  ServicesRoute: ServicesRoute,
  TendersRoute: TendersRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  ScheduleDemoSuccessRoute: ScheduleDemoSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
