/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MobileEntryRouteImport } from './routes/mobile-entry'
import { Route as IvanOsRouteImport } from './routes/ivan-os'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as EnterpriseCrmRouteImport } from './routes/enterprise-crm'
import { Route as CrmWorkspaceRouteImport } from './routes/crm-workspace'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthWorkspaceRouteImport } from './routes/auth-workspace'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'

const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileEntryRoute = MobileEntryRouteImport.update({
  id: '/mobile-entry',
  path: '/mobile-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const IvanOsRoute = IvanOsRouteImport.update({
  id: '/ivan-os',
  path: '/ivan-os',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseCrmRoute = EnterpriseCrmRouteImport.update({
  id: '/enterprise-crm',
  path: '/enterprise-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmWorkspaceRoute = CrmWorkspaceRouteImport.update({
  id: '/crm-workspace',
  path: '/crm-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWorkspaceRoute = AuthWorkspaceRouteImport.update({
  id: '/auth-workspace',
  path: '/auth-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth-workspace': typeof AuthWorkspaceRoute
  '/contact': typeof ContactRoute
  '/crm-workspace': typeof CrmWorkspaceRoute
  '/enterprise-crm': typeof EnterpriseCrmRoute
  '/insights': typeof InsightsRoute
  '/ivan-os': typeof IvanOsRoute
  '/mobile-entry': typeof MobileEntryRoute
  '/services': typeof ServicesRoute
  '/tenders': typeof TendersRoute
  '/admin/settings': typeof AdminSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth-workspace': typeof AuthWorkspaceRoute
  '/contact': typeof ContactRoute
  '/crm-workspace': typeof CrmWorkspaceRoute
  '/enterprise-crm': typeof EnterpriseCrmRoute
  '/insights': typeof InsightsRoute
  '/ivan-os': typeof IvanOsRoute
  '/mobile-entry': typeof MobileEntryRoute
  '/services': typeof ServicesRoute
  '/tenders': typeof TendersRoute
  '/admin/settings': typeof AdminSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth-workspace': typeof AuthWorkspaceRoute
  '/contact': typeof ContactRoute
  '/crm-workspace': typeof CrmWorkspaceRoute
  '/enterprise-crm': typeof EnterpriseCrmRoute
  '/insights': typeof InsightsRoute
  '/ivan-os': typeof IvanOsRoute
  '/mobile-entry': typeof MobileEntryRoute
  '/services': typeof ServicesRoute
  '/tenders': typeof TendersRoute
  '/admin/settings': typeof AdminSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth-workspace'
    | '/contact'
    | '/crm-workspace'
    | '/enterprise-crm'
    | '/insights'
    | '/ivan-os'
    | '/mobile-entry'
    | '/services'
    | '/tenders'
    | '/admin/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth-workspace'
    | '/contact'
    | '/crm-workspace'
    | '/enterprise-crm'
    | '/insights'
    | '/ivan-os'
    | '/mobile-entry'
    | '/services'
    | '/tenders'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth-workspace'
    | '/contact'
    | '/crm-workspace'
    | '/enterprise-crm'
    | '/insights'
    | '/ivan-os'
    | '/mobile-entry'
    | '/services'
    | '/tenders'
    | '/admin/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthWorkspaceRoute: typeof AuthWorkspaceRoute
  ContactRoute: typeof ContactRoute
  CrmWorkspaceRoute: typeof CrmWorkspaceRoute
  EnterpriseCrmRoute: typeof EnterpriseCrmRoute
  InsightsRoute: typeof InsightsRoute
  IvanOsRoute: typeof IvanOsRoute
  MobileEntryRoute: typeof MobileEntryRoute
  ServicesRoute: typeof ServicesRoute
  TendersRoute: typeof TendersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-entry': {
      id: '/mobile-entry'
      path: '/mobile-entry'
      fullPath: '/mobile-entry'
      preLoaderRoute: typeof MobileEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ivan-os': {
      id: '/ivan-os'
      path: '/ivan-os'
      fullPath: '/ivan-os'
      preLoaderRoute: typeof IvanOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-crm': {
      id: '/enterprise-crm'
      path: '/enterprise-crm'
      fullPath: '/enterprise-crm'
      preLoaderRoute: typeof EnterpriseCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-workspace': {
      id: '/crm-workspace'
      path: '/crm-workspace'
      fullPath: '/crm-workspace'
      preLoaderRoute: typeof CrmWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-workspace': {
      id: '/auth-workspace'
      path: '/auth-workspace'
      fullPath: '/auth-workspace'
      preLoaderRoute: typeof AuthWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthWorkspaceRoute: AuthWorkspaceRoute,
  ContactRoute: ContactRoute,
  CrmWorkspaceRoute: CrmWorkspaceRoute,
  EnterpriseCrmRoute: EnterpriseCrmRoute,
  InsightsRoute: InsightsRoute,
  IvanOsRoute: IvanOsRoute,
  MobileEntryRoute: MobileEntryRoute,
  ServicesRoute: ServicesRoute,
  TendersRoute: TendersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
